[package]
name = "node-api"
version = "0.1.0"
authors = ["Jupp MÃ¼ller <jupp0r@gmail.com>"]

[lib]
crate-type = ["lib"]

[dependencies]
node-api-sys = {path = "./node-api-sys"}
futures = "0.1"

[workspace]
members = [
    "examples/hello-world",
    "node-api-sys",
    "tests",
]